### ISSUE TITLE
SME Review

### ISSUE THREAD

**Issue by volosied** [OpenLiberty/guide-jakarta-websocket#8]
Notes for Jakarta WebSocket Guide

Looks really good overall. Just a few suggestions with the wording.  

- `First, the clients make connection over to the server by using HTTP. The server can broadcast messages to the clients. `
->
`First, each client makes a connection over to the server by using HTTP. The server can then broadcast messages to the clients.`

-  `The @ServerEndpoint annotation specifies the value attribute for the connection endpoint` 
-> 
`The @ServerEndpoint's value attribute specifies the URI for where the endpoint will be deployed. `

- `According to the option value` 
->  
`The option parameter signifies which message to construct, either system load, memory usage data, or both. sends out the JsonObject message` 

- `build WebSocket connection` - > `build a WebSocket connection`

- `subscribe on` -> `subscribe to` 

- What is persistent = false ?  Just curious, no real need to include it in the guide. 

- How can one run the tests outside of dev mode?  I tried mvn test, but no luck?

**Comment by volosied** [comment]
`The required WebSocket`  should it be lower case?  Then again, it's capitalized everywhere.

**Comment by shin19991207** [comment]
> How can one run the tests outside of dev mode? I tried mvn test, but no luck?

You can run the test with `mvn failsafe:integration-test` goal, similar to https://github.com/OpenLiberty/draft-guide-jakarta-websocket/blob/draft/scripts/testApp.sh

**Comment by shin19991207** [comment]
> What is persistent = false ? Just curious, no real need to include it in the guide.

https://www.ibm.com/docs/en/was/9.0.5?topic=dea-creating-timers-using-ejb-timer-service-enterprise-beans

"Non-persistent timers have many of the same semantics and behavior as persistent timers, but without the overhead of a data store. Non-persistent timers have a different life cycle than persistent timers. Where persistent timers are maintained across application server shutdowns and restarts, non-persistent timers are active only while the application server is active. Unlike persistent timers, there are no commands to find or cancel non-persistent timers. Non-persistent timers are canceled when the application server is stopped or fails to remain in an active state."

We could remove `persistent = false` from the guide.

**Comment by shin19991207** [comment]
> What is persistent = false ? Just curious, no real need to include it in the guide.

https://www.ibm.com/docs/en/was/9.0.5?topic=dea-creating-timers-using-ejb-timer-service-enterprise-beans

We tried setting `persistence = false` but then the table at http://localhost:9080/ is not updating. We believe that `persistence = false` is required for the timer to function properly.

**Comment by shin19991207** [comment]
Addressed in https://github.com/OpenLiberty/draft-guide-jakarta-websocket/pull/9

**Comment by gkwan-ibm** [comment]
ref: https://github.com/OpenLiberty/guides-common/issues/34
